# =========================
# Dataset-specific Training Configuration
epochs: 10
train_bs: 16
valid_bs: 32  # train_bs * 2
n_accumulate: 1 # Gradient Accumulation
use_amp: true  # Automatic Mixed Precision

# =========================
# Learning Rate & Weight Decay (dataset-specific tuning)
# H-Branch: High Dimensional Feature Map Branch
# M-Branch: Middle Dimensional Feature Map Branch

lr:
  backbone: 5e-4
  h_branch_encoder: 1e-5
  m_branch_encoder: 1e-5 
  head: 5e-4

min_lr: 1e-7

weight_decay:
  backbone: 0.01
  h_branch_encoder: 0.01
  m_branch_encoder: 0.01
  head: 0.01